# todo-bot configuration
todo:
  keyword: ["TODO:"] # string|string[]
  bodyKeyword: ["//"] # string|string[]
  blobLines: 10                # number|boolean, 0 or false to disable
  autoAssign: true            # string|string[]|boolean
  label: true                 # boolean|string|string[]
  reopenClosed: true          # boolean
